
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Portio"

[params]
blogPageURL = "blog"
contactLink = "https://wa.me/6285727679755"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"


# Social icons

[[params.social]]
icon = "fa-linkedin"
url = "https://www.linkedin.com/risangkuncoro"
weight = 2
[[params.social]]
icon = "fa-instagram"
url = "https://www.instagram.com/uiuxforfun"
weight = 3
[[params.social]]
icon = "fa-dribbble"
url = "https://dribbble.com/risangkuncoro"
weight = 4
